apiVersion: v1
kind: Service
metadata:
  name: udagram-api-user
  labels:
    run: udagram-api-user
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: udagram-api-user